<?php

return [
    'items' => [
        ['route' => 'dashboard', 'image' => 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Travel%20and%20places/House.png', 'label' => 'Ana Sayfa', 'sub' => 'Genel Bakış', 'module' => null, 'permission' => 'dashboard.view'],
        ['route' => 'vehicles.index', 'image' => 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Travel%20and%20places/Oncoming%20Automobile.png', 'label' => 'Araçlar', 'sub' => 'Filo Yönetimi', 'module' => 'vehicles', 'permission' => 'vehicles.view'],
        ['route' => 'vehicle-tracking.index', 'image' => 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Travel%20and%20places/Satellite.png', 'label' => 'Araç Takip', 'sub' => 'Canlı İzleme', 'module' => 'vehicles', 'permission' => 'vehicles.view'],
        ['route' => 'drivers.index', 'image' => 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/People/Man%20Pilot.png', 'label' => 'Personeller', 'sub' => 'Personel Yönetimi', 'module' => 'drivers', 'permission' => 'drivers.view'],
        ['route' => 'maintenances.index', 'image' => 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Objects/Wrench.png', 'label' => 'Bakım / Tamir', 'sub' => 'Servis ve Bakım', 'module' => 'maintenances', 'permission' => 'vehicles.view'],
        ['route' => 'fuels.index', 'image' => 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Travel%20and%20places/Fuel%20Pump.png', 'label' => 'Yakıt', 'sub' => 'Yakıt Takibi', 'module' => 'fuels', 'permission' => 'fuels.view'],
        ['route' => 'traffic-penalties.index', 'image' => 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Travel%20and%20places/Police%20Car%20Light.png', 'label' => 'Trafik Cezaları', 'sub' => 'Yasal ve Uyumluluk', 'module' => 'traffic_penalties', 'permission' => 'traffic_penalties.view'],
        ['route' => 'trips.index', 'image' => 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Travel%20and%20places/Motorway.png', 'label' => 'Puantaj / Sefer', 'sub' => 'Operasyon Kayıtları', 'module' => 'trips', 'permission' => 'trips.view'],
        ['route' => 'payrolls.index', 'image' => 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Objects/Money%20Bag.png', 'label' => 'Maaşlar', 'sub' => 'Finansal Kayıtlar', 'module' => 'payrolls', 'permission' => 'payrolls.view'],
        ['route' => 'customers.index', 'image' => 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/People/Handshake.png', 'label' => 'Müşteriler', 'sub' => 'Müşteri Yönetimi', 'module' => 'customers', 'permission' => 'customers.view'],
        ['route' => 'reports.index', 'image' => 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Objects/Bar%20Chart.png', 'label' => 'Raporlar', 'sub' => 'Analiz Merkezi', 'module' => 'reports', 'permission' => 'reports.view'],
        ['route' => 'chat.index', 'image' => 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Smilies/Speech%20Balloon.png', 'label' => 'PilotChat', 'sub' => 'İletişim & Sohbet', 'module' => null, 'permission' => null],
        ['route' => 'activity-logs.index', 'image' => 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Objects/Scroll.png', 'label' => 'LOGLAR', 'sub' => 'Aktivite Kayıtları', 'module' => null, 'permission' => 'logs.view', 'admin_only' => true],
        ['route' => 'company-users.index', 'image' => 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/People/Busts%20in%20Silhouette.png', 'label' => 'Kullanıcılar', 'sub' => 'Erişim Kontrolü', 'module' => null, 'permission' => 'company_users.view'],
        ['route' => 'billing.index', 'image' => 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Objects/Credit%20Card.png', 'label' => 'Abonelik & Ödeme', 'sub' => 'Finansal Durum', 'module' => null, 'permission' => null, 'admin_only' => true],
        ['route' => 'support-tickets.index', 'image' => 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Symbols/SOS%20Button.png', 'label' => 'Destek', 'sub' => 'Yardım Masası', 'module' => null, 'permission' => null],
        ['route' => 'pilotcell.dashboard', 'image' => 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Objects/Mobile%20Phone.png', 'label' => 'PilotCell', 'sub' => 'Servis Takip Sistemi', 'module' => 'pilotcell', 'permission' => 'pilotcell.view'],
        ['route' => 'company-settings.edit', 'image' => 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Objects/Gear.png', 'label' => 'Ayarlar', 'sub' => 'Sistem Yapılandırması', 'module' => null, 'permission' => null, 'admin_only' => true],
        ['route' => 'backups.index', 'image' => 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Objects/Floppy%20Disk.png', 'label' => 'Yedeklemeler', 'sub' => 'Veri Güvenliği', 'module' => null, 'permission' => null, 'admin_only' => true],
    ],
];
