<?php

return [
    'items' => [
        ['route' => 'dashboard', 'image' => 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Travel%20and%20places/Rocket.png', 'label' => 'Ana Sayfa', 'sub' => 'Genel Bakış', 'module' => null, 'permission' => 'dashboard.view'],
        ['route' => 'vehicles.index', 'image' => 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Travel%20and%20places/Oncoming%20Automobile.png', 'label' => 'Araçlar', 'sub' => 'Filo Yönetimi', 'module' => 'vehicles', 'permission' => 'vehicles.view'],
        ['route' => 'vehicle-tracking.index', 'image' => 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/People/Man%20Astronaut.png', 'label' => 'Araç Takip', 'sub' => 'Canlı İzleme', 'module' => 'vehicles', 'permission' => 'vehicle_tracking.view'],
        ['route' => 'drivers.index', 'image' => 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/People/Man%20Pilot.png', 'label' => 'Personeller', 'sub' => 'Personel Yönetimi', 'module' => 'drivers', 'permission' => 'drivers.view'],
        ['route' => 'maintenances.index', 'image' => 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/People/Man%20Mechanic.png', 'label' => 'Bakım / Tamir', 'sub' => 'Servis ve Bakım', 'module' => 'maintenances', 'permission' => 'maintenances.view'],
        ['route' => 'fuels.index', 'image' => 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Smilies/Hot%20Face.png', 'label' => 'Yakıt', 'sub' => 'Yakıt Takibi', 'module' => 'fuels', 'permission' => 'fuels.view'],
        ['route' => 'traffic-penalties.index', 'image' => 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Hand%20gestures/Raised%20Hand.png', 'label' => 'Trafik Cezaları', 'sub' => 'Yasal ve Uyumluluk', 'module' => 'traffic_penalties', 'permission' => 'penalties.view'],
        ['route' => 'trips.index', 'image' => 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Travel%20and%20places/Airplane.png', 'label' => 'Puantaj / Sefer', 'sub' => 'Operasyon Kayıtları', 'module' => 'trips', 'permission' => 'trips.view'],
        ['route' => 'payrolls.index', 'image' => 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Objects/Money%20with%20Wings.png', 'label' => 'Maaşlar', 'sub' => 'Finansal Kayıtlar', 'module' => 'payrolls', 'permission' => 'payrolls.view'],
        ['route' => 'customers.index', 'image' => 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Hand%20gestures/Handshake.png', 'label' => 'Müşteriler', 'sub' => 'Müşteri Yönetimi', 'module' => 'customers', 'permission' => 'customers.view'],
        ['route' => 'reports.index', 'image' => 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Smilies/Face%20with%20Monocle.png', 'label' => 'Raporlar', 'sub' => 'Analiz Merkezi', 'module' => 'reports', 'permission' => 'reports.view'],
        ['route' => 'chat.index', 'image' => 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Smilies/Speech%20Balloon.png', 'label' => 'PilotChat', 'sub' => 'İletişim & Sohbet', 'module' => null, 'permission' => 'chat.view'],
        ['route' => 'activity-logs.index', 'image' => 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Smilies/Nerd%20Face.png', 'label' => 'LOGLAR', 'sub' => 'Aktivite Kayıtları', 'module' => null, 'permission' => 'logs.view'],
        ['route' => 'company-users.index', 'image' => 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/People/People%20Hugging.png', 'label' => 'Kullanıcılar', 'sub' => 'Erişim Kontrolü', 'module' => null, 'permission' => 'company_users.view'],
        ['route' => 'billing.index', 'image' => 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Hand%20gestures/Thumbs%20Up.png', 'label' => 'Abonelik & Ödeme', 'sub' => 'Lisans Yönetimi', 'module' => null, 'permission' => 'billing.view'],
        ['route' => 'support-tickets.index', 'image' => 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Hand%20gestures/Open%20Hands.png', 'label' => 'Destek', 'sub' => 'Yardım Masası', 'module' => null, 'permission' => 'support.view'],
        ['route' => 'pilotcell.dashboard', 'image' => 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Hand%20gestures/Call%20Me%20Hand.png', 'label' => 'PilotCell', 'sub' => 'Servis Takip Sistemi', 'module' => 'pilotcell', 'permission' => 'pilotcell.view'],
        ['route' => 'company-settings.edit', 'image' => 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Hand%20gestures/Crossed%20Fingers.png', 'label' => 'Ayarlar', 'sub' => 'Sistem Yapılandırması', 'module' => null, 'permission' => 'settings.view'],
        ['route' => 'backups.index', 'image' => 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Smilies/Sparkles.png', 'label' => 'Yedeklemeler', 'sub' => 'Veri Güvenliği', 'module' => null, 'permission' => 'backups.view'],
    ],
];
