<?php

/**
 * Deprecated stub – was generated by mistake (nested Http/Controllers).
 * Real controller: App\Http\Controllers\VehicleController
 *
 * Kept as empty file because underlying filesystem disallows deletion.
 * Not referenced anywhere in routes, views or services.
 */

// namespace intentionally left empty — hiçbir yerde kullanılmıyor
